theme: jekyll-theme-cayman
title: Welcome to XLK's homepage!
description: Feel free to bookmark this to keep an eye on my project updates
# **Basic Info:**
* Name: *Lam Nguyen*
* CS-Major at Boise State Univ.
* YouTube: *https://www.youtube.com/channel/UC9-E9TM34yY9opG1Yz04Zlg*
* Facebook: *https://www.facebook.com/xlk98*

## **Project**
